//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class object_list
    {
        public int id { get; set; }
        public string black_box { get; set; }
        public string freetime { get; set; }
        public string gear { get; set; }
        public string glue { get; set; }
        public string hotbreak { get; set; }
        public string listerin { get; set; }
        public string pen { get; set; }
        public string phone { get; set; }
        public string red_box { get; set; }
        public string shaft { get; set; }
        public string sneakers { get; set; }
        public string in_box { get; set; }
        public string multi { get; set; }
        public string multi2 { get; set; }
        public string multi3 { get; set; }
        public string top_view { get; set; }
    }
}
